---
- name: Setup Docker on Remote Server
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes